function d = designFilterLP(Fpass, Fstop, Apass, Astop, sr)
% Design a low-pass filter.

d = designfilt('lowpassiir', ...
  'PassbandFrequency',Fpass,'StopbandFrequency',Fstop, ...
  'PassbandRipple',Apass,'StopbandAttenuation',Astop, ...
  'DesignMethod','butter','SampleRate',sr);